//! WarpReactor6835: zero-copy binary framing decoder generated by PushForge Engine.

use std::io::{self, Read};

#[derive(Debug, thiserror::Error)]
pub enum FrameError {
    #[error("io error: {0}")]
    Io(#[from] io::Error),
    #[error("bad magic")]
    BadMagic,
    #[error("payload too large")]
    Oversize,
}

pub struct Frame<'a> {
    pub kind: u16,
    pub payload: &'a [u8],
}

pub struct Decoder {
    buf: Vec<u8>,
    max_payload: usize,
}

impl Decoder {
    pub fn new(max_payload: usize) -> Self {
        Self { buf: Vec::with_capacity(4096), max_payload }
    }

    pub fn feed<R: Read>(&mut self, mut r: R) -> Result<(), FrameError> {
        let mut chunk = [0u8; 4096];
        loop {
            let n = r.read(&mut chunk)?;
            if n == 0 { return Ok(()); }
            self.buf.extend_from_slice(&chunk[..n]);
        }
    }

    pub fn next<'a>(&'a mut self) -> Result<Option<Frame<'a>>, FrameError> {
        if self.buf.len() < 8 { return Ok(None); }
        if &self.buf[..2] != b"PF" { return Err(FrameError::BadMagic); }
        let kind = u16::from_le_bytes([self.buf[2], self.buf[3]]);
        let len = u32::from_le_bytes([self.buf[4], self.buf[5], self.buf[6], self.buf[7]]) as usize;
        if len > self.max_payload { return Err(FrameError::Oversize); }
        if self.buf.len() < 8 + len { return Ok(None); }
        Ok(Some(Frame { kind, payload: &self.buf[8..8 + len] }))
    }
}
